# Generated by Django 3.2.16 on 2022-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('light', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'plantstatus',
            },
        ),
    ]
